// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModeloDataProveedor.DataModel;

#nullable disable

namespace ModeloDataProveedor.Migrations
{
    [DbContext(typeof(MyAppContext))]
    [Migration("20230121205519_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ModeloDataProveedor.DataModel.Roles", b =>
                {
                    b.Property<string>("Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(50)")
                        .HasDefaultValue("True")
                        .HasColumnOrder(2);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Rol");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Rol = "Administrador",
                            Id = 0
                        },
                        new
                        {
                            Rol = "Usuario",
                            Id = 0
                        },
                        new
                        {
                            Rol = "Proveedor",
                            Id = 0
                        });
                });

            modelBuilder.Entity("ModeloDataProveedor.DataModel.Usuario", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(5);

                    b.Property<string>("Apellido")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(3);

                    b.Property<bool>("Estado")
                        .HasColumnType("BIT")
                        .HasColumnOrder(9);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(8);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(2);

                    b.Property<string>("Password")
                        .HasColumnType("VARCHAR(250)")
                        .HasColumnOrder(6);

                    b.Property<string>("Password2")
                        .HasColumnType("VARCHAR(250)")
                        .HasColumnOrder(7);

                    b.Property<int>("RolId")
                        .HasColumnType("INT")
                        .HasColumnOrder(10);

                    b.Property<string>("UserName")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(4);

                    b.HasKey("Email");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
